"""Add SearchAPI enhanced columns

Revision ID: a7a162425d62
Revises: 
Create Date: 2025-10-20 17:55:10.671815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a162425d62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addresses_list', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('addresses_structured', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('zestimate_values', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('property_details', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('alternative_names', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_column('alternative_names')
        batch_op.drop_column('property_details')
        batch_op.drop_column('zestimate_values')
        batch_op.drop_column('addresses_structured')
        batch_op.drop_column('addresses_list')

    # ### end Alembic commands ###
